### ISSUE TITLE
Help to install the script on Mac

### ISSUE THREAD

**Issue by Teicu** [jaeles-project/gospider#1]
Hi 

can you please explain how can I install this tool in Mac? 

Thanks 

```
Pentest@tools ~ % sudo go get -u github.com/jaeles-project/gospider
Password:
Pentest@tools~ % gospider -s "https://google.com/" -o output -c 10 -d 1
zsh: command not found: gospider
```

**Comment by theblackturtle** [comment]
Did you set $GOPATH? Or you can download binary at https://github.com/jaeles-project/gospider/releases

**Comment by bughuntercat** [comment]
I get the same problem on Linux. Seems to be a module have a different path as the required.

`cp@cp ~ $ go get github.com/jaeles-project/gospider
go get: github.com/jaeles-project/gospider@v1.1.0: parsing go.mod:
	module declares its path as: github.com/theblackturtle/gospider
	        but was required as: github.com/jaeles-project/gospider
`

**Comment by theblackturtle** [comment]
Can you try again. I fixed it.

**Comment by Teicu** [comment]
done, thanks

**Comment by abdilahrf** [comment]
occurs again #9
