### ISSUE TITLE
Silent option

### ISSUE THREAD

**Issue by AnotherWayIn** [jaeles-project/gospider#17]
An option to suppress all the output would be good please
thanks

**Comment by j3ssie** [comment]
Please check out the `-q` option.

**Comment by AnotherWayIn** [comment]
Ah how did i miss that. thanks

p.s it should be "--quiet" not "--quite" 👍

**Comment by j3ssie** [comment]
Thank you. Just fixed the typo too.

**Comment by AnotherWayIn** [comment]
Ah i meant show no output at all. i'm already using the -o so didn't want anything in the console. 
thanks
