### ISSUE TITLE
Subdomains are not shown in output

### ISSUE THREAD

**Issue by dark-warlord14** [jaeles-project/gospider#28]
Hey, since the last update the gospider tool is not showing subdomains in output. I have checked this with multiple flags but it's not working.

![image](https://user-images.githubusercontent.com/25666147/107852000-e1771f80-6e33-11eb-93ca-6e4a5924b30f.png)

The line with the pointed arrow is now missing from gospider output.

Can you please add it back?

Best,

**Comment by j3ssie** [comment]
This should be fixed now with the latest update.
