### ISSUE TITLE
Too many open files

### ISSUE THREAD

**Issue by arthur4ires** [jaeles-project/gospider#36]
Command:
gospider -S "urls files" -o outuputfles -c 5 -t 100 -d 2 --other-source -v --robots --sitemap -u web 

Error:
[0024] ERROR Failed to open file to write Output: open *********/target_folder : too many open files

**Comment by bsysop** [comment]
Hey buddy!

This issue is not from `gospider` but from your computer config.

https://rtcamp.com/tutorials/linux/increase-open-files-limit/

Good luck!.

**Comment by arthur4ires** [comment]
Hope you're well :)

Thank you very much for the answer, I will read the article and make the settings on my server.

**Comment by arthur4ires** [comment]
Apparently, problem solved. Thank you again :)
