### ISSUE TITLE
Update the release binary

### ISSUE THREAD

**Issue by g33kyshivam** [jaeles-project/gospider#9]
Can you please update the binary to the latest commit. I don't know how to install go projects from the source itself and install it.

**Comment by JeffreyShran** [comment]
If you've installed golang, just run `go get github.com/jaeles-project/gospider`

**Comment by abdilahrf** [comment]
![image](https://user-images.githubusercontent.com/6015012/87078556-0c224980-c24f-11ea-8fda-da586eb8760e.png)
weird

**Comment by Bedrovelsen** [comment]
Try 
```
go get -u github.com/user/goRepo/... 
```

or git clone the gospider Repo then cd into the Repo directory then 
```
go build .

cp gospider /your/desired/path/bin/
```
